#!/usr/bin/env bash

# change to directory this script is in
cd "$(dirname "$0")"

cd ..

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk use java 11.0.25-zulu
mvn package
